#!/bin/bash

faces=(Bhagirati)
styles=(Regular Bold Italic)
desc_long="Pan Bengali font designed to support all the languages using the Bengali script."

export nlci=$HOME/script/tools
export src=source
source ${nlci}/prepare.bash

source ${nlci}/metadata.bash

rm -f ${src}/*-???*.sfd*
echo "done producing UFO sources"
