#!/bin/bash

faces="Bhagirati"
styles=(Regular Bold Italic)
desc_long="Pan Bengali font designed to support all the languages using the Bengali script."

export nlci=$HOME/script/tools
source ${nlci}/prepare.bash

source ${nlci}/addchars.bash

source ${nlci}/metadata.bash
echo "done producing UFO sources"
